# -*- coding: utf-8 -*-
"""data_preprocessing_v2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9z_9D5FEFzmQ4R3fpumNzKj3LKeMUYa
"""

import pandas as pd
import numpy as np

df = pd.read_csv('healthcare_data_10k.csv')

# 1. Complex Cleaning: Conditional Imputation
# Instead of a simple mean, we fill missing billing based on Admission Type
df['Billing_Amount'] = df.groupby('Admission_Type')['Billing_Amount'].transform(lambda x: x.fillna(x.median()))

# 2. Feature Engineering: Risk Scoring
# Creating a 'Risk_Score' based on Age and Condition
condition_weights = {'Cancer': 5, 'Diabetes': 4, 'Hypertension': 3, 'Asthma': 2, 'Obesity': 2, 'Arthritis': 1}
df['Condition_Weight'] = df['Medical_Condition'].map(condition_weights)
df['Patient_Risk_Score'] = (df['Age'] * 0.1) + df['Condition_Weight']

# 3. Binning for Categorical Analysis
df['Age_Group'] = pd.cut(df['Age'], bins=[0, 18, 45, 65, 100], labels=['Minor', 'Adult', 'Senior', 'Super_Senior'])

df.to_csv('advanced_cleaned_healthcare.csv', index=False)
print("Advanced Feature Engineering Complete.")