# -*- coding: utf-8 -*-
"""predictive_modeling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1adbmanBGDEQlfsh99VIDJKKshRPCUWOz
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Load engineered data from previous step
df = pd.read_csv('advanced_cleaned_healthcare.csv')

# 1. Feature Selection & Encoding
# Converting categorical text into numbers for the model
le = LabelEncoder()
df['Gender_Enc'] = le.fit_transform(df['Gender'])
df['Condition_Enc'] = le.fit_transform(df['Medical_Condition'])

# Defining Features (X) and Target (y)
X = df[['Age', 'Gender_Enc', 'Condition_Enc', 'Patient_Risk_Score', 'Billing_Amount']]
y = df['Test_Results']

# 2. Train/Test Split (80% Training, 20% Testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Model Training
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# 4. Evaluation
y_pred = rf_model.predict(X_test)
print("--- Machine Learning Model Performance ---")
print(classification_report(y_test, y_pred))